vich_uploader:
    db_driver: orm

    mappings:
        profil:
            uri_prefix: /images/profil # Chemin d'accès aux images
            upload_destination: "%kernel.project_dir%/public/images/profil" # Répertoire où les images seront téléchargées
            namer: Vich\UploaderBundle\Naming\OrignameNamer # Utilisez le nom d'origine du fichier pour le nommage
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
