version: "3.9"

services:
      www:
            build: apache
            container_name: www_arosaje
            ports:
                  - "8742:80"
            volumes:
                  - ./apache/vhosts:/etc/apache2/sites-enabled
                  - ./:/var/www
            restart: always
            networks:
                  - dev

      db:
            image: mysql
            container_name: db_arosaje
            restart: always
            volumes:
                  - db-arosaje-data:/var/lib/mysql
            environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            networks:
                  - dev

      phpmyadmin:
            image: phpmyadmin
            container_name: phpmyadmin_arosaje
            restart: always
            depends_on:
                  - db
            ports:
                  - 8187:80
            environment:
                  PMA_HOST: db
            networks:
                  - dev

      maildev:
            image: maildev/maildev
            container_name: maildev_arosaje
            command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
            ports:
                  - "8185:80"
            restart: always
            networks:
                  - dev

      reactapp:
            build:
                  context: ./reactJs
                  dockerfile: Dockerfile
            container_name: reactapp_arosaje
            ports:
                  - "3120:3000"
            volumes:
                  - ./reactJs:/app
            environment:
                  - NODE_ENV=development
            command: npm start
            restart: always
            networks:
                  - dev

networks:
      dev:


volumes:
      db-arosaje-data:
