version: "3.9"

services:
  www:
    build: ./apache
    container_name: www_arosaje
    depends_on:
      - db
    ports:
      - "8742:80"       # Port pour Apache
      - "9003:9003"     # Port pour Xdebug
    volumes:
      - ./apache/vhosts:/etc/apache2/sites-enabled   # Configuration des vhosts
      - ./:/var/www                                 # Montage du code source
    environment:
      - PHP_IDE_CONFIG=serverName=localhost         # Configuration pour Xdebug IDE
    restart: always
    networks:
      - dev

  db:
    image: mysql:8.0                                # Utilisation d'une version spécifique
    container_name: db_arosaje
    restart: always
    volumes:
      - db-arosaje-data:/var/lib/mysql              # Volume pour persister les données MySQL
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: arosaje                       # Création d'une base de données par défaut
      MYSQL_USER: user                              # Ajout d'un utilisateur par défaut
      MYSQL_PASSWORD: password
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_arosaje
    restart: always
    depends_on:
      - db
    ports:
      - "8187:80"                                   # Accès à phpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""                       # Aucun mot de passe root par défaut
    networks:
      - dev

  maildev:
    image: maildev/maildev:latest
    container_name: maildev_arosaje
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8185:80"                                   # Accès à MailDev via HTTP
    restart: always
    networks:
      - dev

  reactapp:
    build:
      context: ./reactJs
      dockerfile: Dockerfile
    container_name: reactapp_arosaje
    ports:
      - "3120:3000"                                 # Port pour React
    volumes:
      - ./reactJs:/app                              # Montage du code React
    environment:
      - NODE_ENV=development                        # Mode développement
    command: npm start                              # Lancement de l'application React
    restart: always
    networks:
      - dev

networks:
  dev:                                              # Réseau "dev" pour interconnecter les services

volumes:
  db-arosaje-data:                                  # Volume pour stocker les données de MySQL